<?php

/**
 * Content Widgets
 *
 * @author    Josh Johnson <josh@augustash.com>
 * @copyright Copyright (c) 2021 August Ash (https://www.augustash.com)
 */

/** @var \Augustash\ContentWidgets\Block\Widget\Callout\Custom $block */
/** @var \Magento\Framework\Escaper $escaper */

$additionalCssClasses = 'callout-' . $block->getDisplayMode();
$additionalCssClasses .= $block->getBreakoutParentContainer() ? ' breakout-of-parent' : '';
$additionalCssClasses .= $block->getInvertedColor() ? ' inverted-color' : '';
?>
<div class="callout-widget custom <?= $escaper->escapeHtmlAttr($additionalCssClasses) ?>">
    <div class="callout-wrapper">
        <div class="callout-image">
            <img src="<?= $escaper->escapeUrl($block->getImage()) ?>" alt="<?= $escaper->escapeHtml($block->getLabel()) ?>" />
        </div>
        <div class="callout-content">
            <div class="callout-header">
                <strong><?= $escaper->escapeHtml($block->getHeading()) ?></strong>
            </div>
            <?php if ($block->getSubtitle()): ?>
                <div class="callout-subtitle">
                    <em><?= $escaper->escapeHtml($block->getSubtitle()) ?></em>
                </div>
            <?php endif; ?>
            <div class="callout-text">
                <?= $escaper->escapeHtml($block->getDescription(), $block->getAllowedHtmlTags()) ?>
            </div>
            <?php if ($block->getHref() && $block->getLabel()): ?>
                <div class="callout-buttons">
                    <div class="callout-primary">
                        <a <?= /* @noEscape */ $block->getLinkAttributes() ?>>
                            <span class="action primary"><?= $escaper->escapeHtml($block->getLabel()) ?></span>
                        </a>
                    </div>
                </div>
            <?php endif; ?>
        </div>
    </div>
</div>
