<?php

/**
 * Content Widgets
 *
 * @author    Josh Johnson <josh@augustash.com>
 * @copyright Copyright (c) 2021 August Ash (https://www.augustash.com)
 */

/** @var \Augustash\ContentWidgets\Block\Widget\Callout\Custom $block */
/** @var \Magento\Framework\Escaper $escaper */

$additionalCssClasses = 'callout-' . $block->getDisplayMode();
$additionalCssClasses .= $block->getBreakoutParentContainer() ? ' breakout-of-parent' : '';
?>
<div class="callout-widget custom <?= $block->escapeHtmlAttr($additionalCssClasses) ?>">
    <div class="callout-wrapper">
        <div class="callout-image">
            <img src="<?= $block->escapeUrl($block->getImage()) ?>" alt="<?= $block->escapeHtml($block->getLabel()) ?>" />
        </div>
        <div class="callout-content">
            <div class="callout-header">
                <strong><?= $block->escapeHtml($block->getHeading()) ?></strong>
            </div>
            <?php if ($block->getSubtitle()): ?>
                <div class="callout-subtitle">
                    <em><?= $block->escapeHtml($block->getSubtitle()) ?></em>
                </div>
            <?php endif; ?>
            <p class="callout-text">
                <?= $block->escapeHtml($block->getDescription(), ['ul', 'li', 'a', 'p', 'strong', 'em', 'br']) ?>
            </p>
            <?php if ($block->getHref()): ?>
                <div class="callout-buttons">
                    <div class="callout-primary">
                        <a <?= $block->escapeHtmlAttr($block->getLinkAttributes()) ?>>
                            <span class="action primary"><?= $block->escapeHtml($block->getLabel()) ?></span>
                        </a>
                    </div>
                </div>
            <?php endif; ?>
        </div>
    </div>
</div>
